/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javafx.scene.image.ImageView;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author yeico
 */
public class JFrameMain extends javax.swing.JFrame {
    private JButton nextButton = new JButton();
    private JButton backButton = new JButton();
    private JPanel panel = new JPanel();
    private int index = 0;
    
    private JFrame[] frameProtocols = {new JFrameUtopia(), new JFrameStopAndWait(), new JFramePAR(), 
        new JFrameSlidingWindow(), new JFrameGoBack(), new JFrameSelectiveRepeat()};

    /**
     * Creates new form Main_window
     */
    public JFrameMain() {
        initComponents();
        this.setTitle("Protocol Simulator");
        this.setSize(1300,700);
        this.setLocationRelativeTo(null);
        // Crear el panel y agregar las ventanas
        
        panel.setBounds(0, 0, this.getWidth(), this.getHeight());
        panel.setBackground(Color.black);
        panel.add(frameProtocols[index].getContentPane());
        backButton.setBounds(10, 300, 100, this.getHeight()-600);
        nextButton.setBounds(1180, 300, 100, this.getHeight()-600);
        //----------------------------------------
        ImageIcon img = new ImageIcon(getClass().getResource("/Images/next-arrow.png"));
        Icon icon = new ImageIcon(img.getImage().getScaledInstance(nextButton.getWidth(),nextButton.getHeight(),Image.SCALE_AREA_AVERAGING));
        nextButton.setIcon(icon);
        
        img = new ImageIcon(getClass().getResource("/Images/back-arrow.png"));
        icon = new ImageIcon(img.getImage().getScaledInstance(backButton.getWidth(),backButton.getHeight(),Image.SCALE_AREA_AVERAGING));
        backButton.setIcon(icon);
        //--------------------------------
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panel.remove(frameProtocols[index].getContentPane());
                index = (index - 1 + frameProtocols.length) % frameProtocols.length;
                panel.add(frameProtocols[index].getContentPane());
                panel.updateUI();
                backButton.updateUI();
                nextButton.updateUI();
            }

        });
        nextButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panel.remove(frameProtocols[index].getContentPane());
                index = (index + 1) % frameProtocols.length;
                panel.add(frameProtocols[index].getContentPane());
                panel.updateUI();
                backButton.updateUI();
                nextButton.updateUI();
            }
        });
        //-------------------------------------------------
        this.add(backButton);
        this.add(nextButton);
        this.add(panel);
        setResizable(false);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(200, 400));
        setSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMain().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
